[package]
edition = "2024"
name = "axplat-aarch64-dyn"
version = "0.1.0"

[dependencies]
axconfig-macros = "0.2"
axcpu = {git = "https://github.com/arceos-org/axcpu.git"}
axplat = {git = "https://github.com/arceos-org/axhal_crates"}
pie-boot = {version = "0.1.8"}

